INSERT INTO countries (country_UUID, country_name, country_short_code, country_call_code, created_at, updated_at) VALUES
    (UUID(), 'Afghanistan', 'AF/AFG', '+93', NOW(), NOW()),
    (UUID(), 'Åland Islands', 'AX', '+358', NOW(), NOW()),
    (UUID(), 'Albania', 'AL', '+355', NOW(), NOW()),
    (UUID(), 'Algeria', 'DZ', '+213', NOW(), NOW()),
    (UUID(), 'American Samoa', 'AS', '+1-684', NOW(), NOW()),
    (UUID(), 'Andorra', 'AD', '+376', NOW(), NOW()),
    (UUID(), 'Angola', 'AO', '+244', NOW(), NOW()),
    (UUID(), 'Anguilla', 'AI', '+1-264', NOW(), NOW()),
    (UUID(), 'Antarctica', 'AQ', '+672', NOW(), NOW()),
    (UUID(), 'Antigua and Barbuda', 'AG', '+1-268', NOW(), NOW()),
    (UUID(), 'Argentina', 'AR', '+54', NOW(), NOW()),
    (UUID(), 'Armenia', 'AM', '+374', NOW(), NOW()),
    (UUID(), 'Aruba', 'AW', '+297', NOW(), NOW()),
    (UUID(), 'Australia', 'AU', '+61', NOW(), NOW()),
    (UUID(), 'Austria', 'AT', '+43', NOW(), NOW()),
    (UUID(), 'Azerbaijan', 'AZ', '+994', NOW(), NOW()),
    (UUID(), 'Bahamas', 'BS', '+1-242', NOW(), NOW()),
    (UUID(), 'Bahrain', 'BH', '+973', NOW(), NOW()),
    (UUID(), 'Bangladesh', 'BD', '+880', NOW(), NOW()),
    (UUID(), 'Barbados', 'BB', '+1-246', NOW(), NOW()),
    (UUID(), 'Belarus', 'BY', '+375', NOW(), NOW()),
    (UUID(), 'Belgium', 'BE', '+32', NOW(), NOW()),
    (UUID(), 'Belize', 'BZ', '+501', NOW(), NOW()),
    (UUID(), 'Benin', 'BJ', '+229', NOW(), NOW()),
    (UUID(), 'Bermuda', 'BM', '+1-441', NOW(), NOW()),
    (UUID(), 'Bhutan', 'BT', '+975', NOW(), NOW()),
    (UUID(), 'Bolivia, Plurinational State of', 'BO', '+591', NOW(), NOW()),
    (UUID(), 'Bonaire, Sint Eustatius and Saba', 'BQ', '+599', NOW(), NOW()),
    (UUID(), 'Bosnia and Herzegovina', 'BA', '+387', NOW(), NOW()),
    (UUID(), 'Botswana', 'BW', '+267', NOW(), NOW()),
    (UUID(), 'Bouvet Island', 'BV', '+47', NOW(), NOW()),
    (UUID(), 'Brazil', 'BR', '+55', NOW(), NOW()),
    (UUID(), 'British Indian Ocean Territory', 'IO', '+246', NOW(), NOW()),
    (UUID(), 'Brunei Darussalam', 'BN', '+673', NOW(), NOW()),
    (UUID(), 'Bulgaria', 'BG', '+359', NOW(), NOW()),
    (UUID(), 'Burkina Faso', 'BF', '+226', NOW(), NOW()),
    (UUID(), 'Burundi', 'BI', '+257', NOW(), NOW()),
    (UUID(), 'Cambodia', 'KH', '+855', NOW(), NOW()),
    (UUID(), 'Cameroon', 'CM', '+237', NOW(), NOW()),
    (UUID(), 'Canada', 'CA', '+1', NOW(), NOW()),
    (UUID(), 'Cape Verde', 'CV', '+238', NOW(), NOW()),
    (UUID(), 'Cayman Islands', 'KY', '+1-345', NOW(), NOW()),
    (UUID(), 'Central African Republic', 'CF', '+236', NOW(), NOW()),
    (UUID(), 'Chad', 'TD', '+235', NOW(), NOW()),
    (UUID(), 'Chile', 'CL', '+56', NOW(), NOW()),
    (UUID(), 'China', 'CN', '+86', NOW(), NOW()),
    (UUID(), 'Christmas Island', 'CX', '+61', NOW(), NOW()),
    (UUID(), 'Cocos (Keeling) Islands', 'CC', '+61', NOW(), NOW()),
    (UUID(), 'Colombia', 'CO', '+57', NOW(), NOW()),
    (UUID(), 'Comoros', 'KM', '+269', NOW(), NOW()),
    (UUID(), 'Congo', 'CG', '+242', NOW(), NOW()),
    (UUID(), 'Congo, the Democratic Republic of the', 'CD', '+243', NOW(), NOW()),
    (UUID(), 'Cook Islands', 'CK', '+682', NOW(), NOW()),
    (UUID(), 'Costa Rica', 'CR', '+506', NOW(), NOW()),
    (UUID(), 'Côte d\'Ivoire', 'CI', '+225', NOW(), NOW()),
    (UUID(), 'Croatia', 'HR', '+385', NOW(), NOW()),
    (UUID(), 'Cuba', 'CU', '+53', NOW(), NOW()),
    (UUID(), 'Curaçao', 'CW', '+599', NOW(), NOW()),
    (UUID(), 'Cyprus', 'CY', '+357', NOW(), NOW()),
    (UUID(), 'Czech Republic', 'CZ', '+420', NOW(), NOW()),
    (UUID(), 'Denmark', 'DK', '+45', NOW(), NOW()),
    (UUID(), 'Djibouti', 'DJ', '+253', NOW(), NOW()),
    (UUID(), 'Dominica', 'DM', '+1-767', NOW(), NOW()),
    (UUID(), 'Dominican Republic', 'DO', '+1-809, +1-829, +1-849', NOW(), NOW()),
    (UUID(), 'Ecuador', 'EC', '+593', NOW(), NOW()),
    (UUID(), 'Egypt', 'EG', '+20', NOW(), NOW()),
    (UUID(), 'El Salvador', 'SV', '+503', NOW(), NOW()),
    (UUID(), 'Equatorial Guinea', 'GQ', '+240', NOW(), NOW()),
    (UUID(), 'Eritrea', 'ER', '+291', NOW(), NOW()),
    (UUID(), 'Estonia', 'EE', '+372', NOW(), NOW()),
    (UUID(), 'Ethiopia', 'ET', '+251', NOW(), NOW()),
    (UUID(), 'Falkland Islands (Malvinas)', 'FK', '+500', NOW(), NOW()),
    (UUID(), 'Faroe Islands', 'FO', '+298', NOW(), NOW()),
    (UUID(), 'Fiji', 'FJ', '+679', NOW(), NOW()),
    (UUID(), 'Finland', 'FI', '+358', NOW(), NOW()),
    (UUID(), 'France', 'FR', '+33', NOW(), NOW()),
    (UUID(), 'French Guiana', 'GF', '+594', NOW(), NOW()),
    (UUID(), 'French Polynesia', 'PF', '+689', NOW(), NOW()),
    (UUID(), 'French Southern Territories', 'TF', '+262', NOW(), NOW()),
    (UUID(), 'Gabon', 'GA', '+241', NOW(), NOW()),
    (UUID(), 'Gambia', 'GM', '+220', NOW(), NOW()),
    (UUID(), 'Georgia', 'GE', '+995', NOW(), NOW()),
    (UUID(), 'Germany', 'DE', '+49', NOW(), NOW()),
    (UUID(), 'Ghana', 'GH', '+233', NOW(), NOW()),
    (UUID(), 'Gibraltar', 'GI', '+350', NOW(), NOW()),
    (UUID(), 'Greece', 'GR', '+30', NOW(), NOW()),
    (UUID(), 'Greenland', 'GL', '+299', NOW(), NOW()),
    (UUID(), 'Grenada', 'GD', '+1-473', NOW(), NOW()),
    (UUID(), 'Guadeloupe', 'GP', '+590', NOW(), NOW()),
    (UUID(), 'Guam', 'GU', '+1-671', NOW(), NOW()),
    (UUID(), 'Guatemala', 'GT', '+502', NOW(), NOW()),
    (UUID(), 'Guernsey', 'GG', '+44-1481', NOW(), NOW()),
    (UUID(), 'Guinea', 'GN', '+224', NOW(), NOW()),
    (UUID(), 'Guinea-Bissau', 'GW', '+245', NOW(), NOW()),
    (UUID(), 'Guyana', 'GY', '+592', NOW(), NOW()),
    (UUID(), 'Haiti', 'HT', '+509', NOW(), NOW()),
    (UUID(), 'Heard Island and McDonald Islands', 'HM', '+61', NOW(), NOW()),
    (UUID(), 'Holy See (Vatican City State)', 'VA', '+379', NOW(), NOW()),
    (UUID(), 'Honduras', 'HN', '+504', NOW(), NOW()),
    (UUID(), 'Hong Kong', 'HK', '+852', NOW(), NOW()),
    (UUID(), 'Hungary', 'HU', '+36', NOW(), NOW()),
    (UUID(), 'Iceland', 'IS', '+354', NOW(), NOW()),
    (UUID(), 'India', 'IN', '+91', NOW(), NOW()),
    (UUID(), 'Indonesia', 'ID', '+62', NOW(), NOW()),
    (UUID(), 'Iran, Islamic Republic of', 'IR', '+98', NOW(), NOW()),
    (UUID(), 'Iraq', 'IQ', '+964', NOW(), NOW()),
    (UUID(), 'Ireland', 'IE', '+353', NOW(), NOW()),
    (UUID(), 'Isle of Man', 'IM', '+44-1624', NOW(), NOW()),
    (UUID(), 'Israel', 'IL', '+972', NOW(), NOW()),
    (UUID(), 'Italy', 'IT', '+39', NOW(), NOW()),
    (UUID(), 'Jamaica', 'JM', '+1-876', NOW(), NOW()),
    (UUID(), 'Japan', 'JP', '+81', NOW(), NOW()),
    (UUID(), 'Jersey', 'JE', '+44-1534', NOW(), NOW()),
    (UUID(), 'Jordan', 'JO', '+962', NOW(), NOW()),
    (UUID(), 'Kazakhstan', 'KZ', '+7', NOW(), NOW()),
    (UUID(), 'Kenya', 'KE', '+254', NOW(), NOW()),
    (UUID(), 'Kiribati', 'KI', '+686', NOW(), NOW()),
    (UUID(), 'Korea, Democratic People\'s Republic of', 'KP', '+850', NOW(), NOW()),
    (UUID(), 'Korea, Republic of', 'KR', '+82', NOW(), NOW()),
    (UUID(), 'Kuwait', 'KW', '+965', NOW(), NOW()),
    (UUID(), 'Kyrgyzstan', 'KG', '+996', NOW(), NOW()),
    (UUID(), 'Lao People\'s Democratic Republic', 'LA', '+856', NOW(), NOW()),
    (UUID(), 'Latvia', 'LV', '+371', NOW(), NOW()),
    (UUID(), 'Lebanon', 'LB', '+961', NOW(), NOW()),
    (UUID(), 'Lesotho', 'LS', '+266', NOW(), NOW()),
    (UUID(), 'Liberia', 'LR', '+231', NOW(), NOW()),
    (UUID(), 'Libya', 'LY', '+218', NOW(), NOW()),
    (UUID(), 'Liechtenstein', 'LI', '+423', NOW(), NOW()),
    (UUID(), 'Lithuania', 'LT', '+370', NOW(), NOW()),
    (UUID(), 'Luxembourg', 'LU', '+352', NOW(), NOW()),
    (UUID(), 'Macao', 'MO', '+853', NOW(), NOW()),
    (UUID(), 'Macedonia, the Former Yugoslav Republic of', 'MK', '+389', NOW(), NOW()),
    (UUID(), 'Madagascar', 'MG', '+261', NOW(), NOW()),
    (UUID(), 'Malawi', 'MW', '+265', NOW(), NOW()),
    (UUID(), 'Malaysia', 'MY', '+60', NOW(), NOW()),
    (UUID(), 'Maldives', 'MV', '+960', NOW(), NOW()),
    (UUID(), 'Mali', 'ML', '+223', NOW(), NOW()),
    (UUID(), 'Malta', 'MT', '+356', NOW(), NOW()),
    (UUID(), 'Marshall Islands', 'MH', '+692', NOW(), NOW()),
    (UUID(), 'Martinique', 'MQ', '+596', NOW(), NOW()),
    (UUID(), 'Mauritania', 'MR', '+222', NOW(), NOW()),
    (UUID(), 'Mauritius', 'MU', '+230', NOW(), NOW()),
    (UUID(), 'Mayotte', 'YT', '+262', NOW(), NOW()),
    (UUID(), 'Mexico', 'MX', '+52', NOW(), NOW()),
    (UUID(), 'Micronesia, Federated States of', 'FM', '+691', NOW(), NOW()),
    (UUID(), 'Moldova, Republic of', 'MD', '+373', NOW(), NOW()),
    (UUID(), 'Monaco', 'MC', '+377', NOW(), NOW()),
    (UUID(), 'Mongolia', 'MN', '+976', NOW(), NOW()),
    (UUID(), 'Montenegro', 'ME', '+382', NOW(), NOW()),
    (UUID(), 'Montserrat', 'MS', '+1-664', NOW(), NOW()),
    (UUID(), 'Morocco', 'MA', '+212', NOW(), NOW()),
    (UUID(), 'Mozambique', 'MZ', '+258', NOW(), NOW()),
    (UUID(), 'Myanmar', 'MM', '+95', NOW(), NOW()),
    (UUID(), 'Namibia', 'NA', '+264', NOW(), NOW()),
    (UUID(), 'Nauru', 'NR', '+674', NOW(), NOW()),
    (UUID(), 'Nepal', 'NP', '+977', NOW(), NOW()),
    (UUID(), 'Netherlands', 'NL', '+31', NOW(), NOW()),
    (UUID(), 'New Caledonia', 'NC', '+687', NOW(), NOW()),
    (UUID(), 'New Zealand', 'NZ', '+64', NOW(), NOW()),
    (UUID(), 'Nicaragua', 'NI', '+505', NOW(), NOW()),
    (UUID(), 'Niger', 'NE', '+227', NOW(), NOW()),
    (UUID(), 'Nigeria', 'NG', '+234', NOW(), NOW()),
    (UUID(), 'Niue', 'NU', '+683', NOW(), NOW()),
    (UUID(), 'Norfolk Island', 'NF', '+672', NOW(), NOW()),
    (UUID(), 'Northern Mariana Islands', 'MP', '+1-670', NOW(), NOW()),
    (UUID(), 'Norway', 'NO', '+47', NOW(), NOW()),
    (UUID(), 'Oman', 'OM', '+968', NOW(), NOW()),
    (UUID(), 'Pakistan', 'PK', '+92', NOW(), NOW()),
    (UUID(), 'Palau', 'PW', '+680', NOW(), NOW()),
    (UUID(), 'Palestine, State of', 'PS', '+970', NOW(), NOW()),
    (UUID(), 'Panama', 'PA', '+507', NOW(), NOW()),
    (UUID(), 'Papua New Guinea', 'PG', '+675', NOW(), NOW()),
    (UUID(), 'Paraguay', 'PY', '+595', NOW(), NOW()),
    (UUID(), 'Peru', 'PE', '+51', NOW(), NOW()),
    (UUID(), 'Philippines', 'PH', '+63', NOW(), NOW()),
    (UUID(), 'Pitcairn', 'PN', '+64', NOW(), NOW()),
    (UUID(), 'Poland', 'PL', '+48', NOW(), NOW()),
    (UUID(), 'Portugal', 'PT', '+351', NOW(), NOW()),
    (UUID(), 'Puerto Rico', 'PR', '+1-787, +1-939', NOW(), NOW()),
    (UUID(), 'Qatar', 'QA', '+974', NOW(), NOW()),
    (UUID(), 'Réunion', 'RE', '+262', NOW(), NOW()),
    (UUID(), 'Romania', 'RO', '+40', NOW(), NOW()),
    (UUID(), 'Russian Federation', 'RU', '+7', NOW(), NOW()),
    (UUID(), 'Rwanda', 'RW', '+250', NOW(), NOW()),
    (UUID(), 'Saint Barthélemy', 'BL', '+590', NOW(), NOW()),
    (UUID(), 'Saint Helena, Ascension and Tristan da Cunha', 'SH', '+290', NOW(), NOW()),
    (UUID(), 'Saint Kitts and Nevis', 'KN', '+1-869', NOW(), NOW()),
    (UUID(), 'Saint Lucia', 'LC', '+1-758', NOW(), NOW()),
    (UUID(), 'Saint Martin (French part)', 'MF', '+590', NOW(), NOW()),
    (UUID(), 'Saint Pierre and Miquelon', 'PM', '+508', NOW(), NOW()),
    (UUID(), 'Saint Vincent and the Grenadines', 'VC', '+1-784', NOW(), NOW()),
    (UUID(), 'Samoa', 'WS', '+685', NOW(), NOW()),
    (UUID(), 'San Marino', 'SM', '+378', NOW(), NOW()),
    (UUID(), 'Sao Tome and Principe', 'ST', '+239', NOW(), NOW()),
    (UUID(), 'Saudi Arabia', 'SA', '+966', NOW(), NOW()),
    (UUID(), 'Senegal', 'SN', '+221', NOW(), NOW()),
    (UUID(), 'Serbia', 'RS', '+381', NOW(), NOW()),
    (UUID(), 'Seychelles', 'SC', '+248', NOW(), NOW()),
    (UUID(), 'Sierra Leone', 'SL', '+232', NOW(), NOW()),
    (UUID(), 'Singapore', 'SG', '+65', NOW(), NOW()),
    (UUID(), 'Sint Maarten (Dutch part)', 'SX', '+1-721', NOW(), NOW()),
    (UUID(), 'Slovakia', 'SK', '+421', NOW(), NOW()),
    (UUID(), 'Slovenia', 'SI', '+386', NOW(), NOW()),
    (UUID(), 'Solomon Islands', 'SB', '+677', NOW(), NOW()),
    (UUID(), 'Somalia', 'SO', '+252', NOW(), NOW()),
    (UUID(), 'South Africa', 'ZA', '+27', NOW(), NOW()),
    (UUID(), 'South Georgia and the South Sandwich Islands', 'GS', '+500', NOW(), NOW()),
    (UUID(), 'South Sudan', 'SS', '+211', NOW(), NOW()),
    (UUID(), 'Spain', 'ES', '+34', NOW(), NOW()),
    (UUID(), 'Sri Lanka', 'LK', '+94', NOW(), NOW()),
    (UUID(), 'Sudan', 'SD', '+249', NOW(), NOW()),
    (UUID(), 'Suriname', 'SR', '+597', NOW(), NOW()),
    (UUID(), 'Svalbard and Jan Mayen', 'SJ', '+47', NOW(), NOW()),
    (UUID(), 'Swaziland', 'SZ', '+268', NOW(), NOW()),
    (UUID(), 'Sweden', 'SE', '+46', NOW(), NOW()),
    (UUID(), 'Switzerland', 'CH', '+41', NOW(), NOW()),
    (UUID(), 'Syrian Arab Republic', 'SY', '+963', NOW(), NOW()),
    (UUID(), 'Taiwan, Province of China', 'TW', '+886', NOW(), NOW()),
    (UUID(), 'Tajikistan', 'TJ', '+992', NOW(), NOW()),
    (UUID(), 'Tanzania, United Republic of', 'TZ', '+255', NOW(), NOW()),
    (UUID(), 'Thailand', 'TH', '+66', NOW(), NOW()),
    (UUID(), 'Timor-Leste', 'TL', '+670', NOW(), NOW()),
    (UUID(), 'Togo', 'TG', '+228', NOW(), NOW()),
    (UUID(), 'Tokelau', 'TK', '+690', NOW(), NOW()),
    (UUID(), 'Tonga', 'TO', '+676', NOW(), NOW()),
    (UUID(), 'Trinidad and Tobago', 'TT', '+1-868', NOW(), NOW()),
    (UUID(), 'Tunisia', 'TN', '+216', NOW(), NOW()),
    (UUID(), 'Turkey', 'TR', '+90', NOW(), NOW()),
    (UUID(), 'Turkmenistan', 'TM', '+993', NOW(), NOW()),
    (UUID(), 'Turks and Caicos Islands', 'TC', '+1-649', NOW(), NOW()),
    (UUID(), 'Tuvalu', 'TV', '+688', NOW(), NOW()),
    (UUID(), 'Uganda', 'UG', '+256', NOW(), NOW()),
    (UUID(), 'Ukraine', 'UA', '+380', NOW(), NOW()),
    (UUID(), 'United Arab Emirates', 'AE', '+971', NOW(), NOW()),
    (UUID(), 'United Kingdom', 'GB', '+44', NOW(), NOW()),
    (UUID(), 'United States', 'US', '+1', NOW(), NOW()),
    (UUID(), 'United States Minor Outlying Islands', 'UM', '+1', NOW(), NOW()),
    (UUID(), 'Uruguay', 'UY', '+598', NOW(), NOW()),
    (UUID(), 'Uzbekistan', 'UZ', '+998', NOW(), NOW()),
    (UUID(), 'Vanuatu', 'VU', '+678', NOW(), NOW()),
    (UUID(), 'Venezuela, Bolivarian Republic of', 'VE', '+58', NOW(), NOW()),
    (UUID(), 'Viet Nam', 'VN', '+84', NOW(), NOW()),
    (UUID(), 'Virgin Islands, British', 'VG', '+1-284', NOW(), NOW()),
    (UUID(), 'Virgin Islands, U.S.', 'VI', '+1-340', NOW(), NOW()),
    (UUID(), 'Wallis and Futuna', 'WF', '+681', NOW(), NOW()),
    (UUID(), 'Western Sahara', 'EH', '+212', NOW(), NOW()),
    (UUID(), 'Yemen', 'YE', '+967', NOW(), NOW()),
    (UUID(), 'Zambia', 'ZM', '+260', NOW(), NOW()),
    (UUID(), 'Zimbabwe', 'ZW', '+263', NOW(), NOW());

INSERT INTO house_types (type_name, type_UUID, type_description, created_at, updated_at) VALUES
    ("Single-Family-Home", UUID(), "A detached home designed for one family, usually with a yard or garden.", NOW(), NOW()),
    ("Condominium-(Condo)", UUID(), "Individual units within a larger building, where residents own their unit but share common areas.", NOW(), NOW()),
    ("Apartment", UUID(), "Units within a larger building, typically rented rather than owned, with shared amenities.", NOW(), NOW()),
    ("Townhouse/Row-House", UUID(), "Multi-story homes with shared walls on one or both sides, often in a row.", NOW(), NOW()),
    ("Duplex/Triplex", UUID(), "A single building divided into two (duplex) or three (triplex) separate units, each with its own entrance.", NOW(), NOW()),
    ("Cottage", UUID(), "A small, often charming, standalone home, typically found in rural or vacation areas.", NOW(), NOW()),
    ("Bungalow", UUID(), "A single-story home with a simple, practical layout, often featuring a front porch.", NOW(), NOW()),
    ("Ranch-House", UUID(), "Single-story, sprawling homes that are typically long and low to the ground, popular in suburban areas.", NOW(), NOW()),
    ("Villa", UUID(), "A large, luxurious home, often in a rural or semi-rural setting, originally from Mediterranean styles.", NOW(), NOW()),
    ("Mansion", UUID(), "A large, luxurious home with multiple bedrooms and extensive grounds.", NOW(), NOW()),
    ("Tiny-House", UUID(), "Compact homes (typically under 400 square feet) focusing on minimalism and efficient space use.", NOW(), NOW()),
    ("Mobile-Home / Manufactured Home", UUID(), "Prefabricated homes that can be transported to different locations, often found in designated communities.", NOW(), NOW()),
    ("Modular-Home", UUID(), "Prefabricated homes assembled on-site from factory-made sections.", NOW(), NOW()),
    ("Cabin", UUID(), "A small, rustic house, usually located in rural or mountainous areas, often made from wood.", NOW(), NOW()),
    ("A-Frame-House", UUID(), "A triangular-shaped house with steeply angled sides, popular in snowy regions.", NOW(), NOW()),
    ("Beach-House", UUID(), "Houses located near the coast, often raised on stilts to protect from tides and floods.", NOW(), NOW()),
    ("Farm-House", UUID(), "A rural house style, often larger and with a simple design, sometimes with attached land for agriculture.", NOW(), NOW()),
    ("Estate", UUID(), "A large property with extensive grounds, often with multiple buildings and luxurious features.", NOW(), NOW()),
    ("Loft", UUID(), "Converted open-space apartments, typically in former industrial buildings, with high ceilings and minimal interior walls.", NOW(), NOW()),
    ("Coach-House / Carriage House", UUID(), "Historically used to house carriages, now often repurposed into unique homes.", NOW(), NOW()),
    ("Yurt", UUID(), "A round, tent-like structure with a wooden frame, traditionally used by nomads, popular for eco-friendly living.", NOW(), NOW()),
    ("Tree-House", UUID(), "A house built among the branches of a tree, often used as a unique dwelling or vacation rental.", NOW(), NOW()),
    ("Earth-Sheltered-House", UUID(), "A partially or fully underground house designed to be energy-efficient.", NOW(), NOW()),
    ("Geodesic-Dome-House", UUID(), "A spherical or semi-spherical house, known for its energy efficiency and resilience.", NOW(), NOW()),
    ("Penthouse", UUID(), "A luxurious unit on the top floor of an apartment or condo building, often with exclusive amenities.", NOW(), NOW()),
    ("Container-Home", UUID(), "Houses made from repurposed shipping containers, popular for sustainability and affordability.", NOW(), NOW()),
    ("Row-House", UUID(), "A continuous line of similar houses, each sharing a wall with its neighbors, common in urban settings.", NOW(), NOW()),
    ("Multi-Family House", UUID(), "A residential building with multiple housing units, suitable for multi-generational families or rental.", NOW(), NOW());

INSERT INTO counties (county_UUID, county_name, created_at, updated_at) VALUES
    (UUID(), 'Mombasa', NOW(), NOW()),
    (UUID(), 'Kwale', NOW(), NOW()),
    (UUID(), 'Kilifi', NOW(), NOW()),
    (UUID(), 'Tana River', NOW(), NOW()),
    (UUID(), 'Lamu', NOW(), NOW()),
    (UUID(), 'Taita Taveta', NOW(), NOW()),
    (UUID(), 'Garissa', NOW(), NOW()),
    (UUID(), 'Wajir', NOW(), NOW()),
    (UUID(), 'Mandera', NOW(), NOW()),
    (UUID(), 'Marsabit', NOW(), NOW()),
    (UUID(), 'Isiolo', NOW(), NOW()),
    (UUID(), 'Meru', NOW(), NOW()),
    (UUID(), 'Tharaka Nithi', NOW(), NOW()),
    (UUID(), 'Embu', NOW(), NOW()),
    (UUID(), 'Kitui', NOW(), NOW()),
    (UUID(), 'Machakos', NOW(), NOW()),
    (UUID(), 'Makueni', NOW(), NOW()),
    (UUID(), 'Nyandarua', NOW(), NOW()),
    (UUID(), 'Nyeri', NOW(), NOW()),
    (UUID(), 'Kirinyaga', NOW(), NOW()),
    (UUID(), 'Murang\'a', NOW(), NOW()),
    (UUID(), 'Kiambu', NOW(), NOW()),
    (UUID(), 'Turkana', NOW(), NOW()),
    (UUID(), 'West Pokot', NOW(), NOW()),
    (UUID(), 'Samburu', NOW(), NOW()),
    (UUID(), 'Trans Nzoia', NOW(), NOW()),
    (UUID(), 'Uasin Gishu', NOW(), NOW()),
    (UUID(), 'Elgeyo Marakwet', NOW(), NOW()),
    (UUID(), 'Nandi', NOW(), NOW()),
    (UUID(), 'Baringo', NOW(), NOW()),
    (UUID(), 'Laikipia', NOW(), NOW()),
    (UUID(), 'Nakuru', NOW(), NOW()),
    (UUID(), 'Narok', NOW(), NOW()),
    (UUID(), 'Kajiado', NOW(), NOW()),
    (UUID(), 'Kericho', NOW(), NOW()),
    (UUID(), 'Bomet', NOW(), NOW()),
    (UUID(), 'Kakamega', NOW(), NOW()),
    (UUID(), 'Vihiga', NOW(), NOW()),
    (UUID(), 'Bungoma', NOW(), NOW()),
    (UUID(), 'Busia', NOW(), NOW()),
    (UUID(), 'Siaya', NOW(), NOW()),
    (UUID(), 'Kisumu', NOW(), NOW()),
    (UUID(), 'Homa Bay', NOW(), NOW()),
    (UUID(), 'Migori', NOW(), NOW()),
    (UUID(), 'Kisii', NOW(), NOW()),
    (UUID(), 'Nyamira', NOW(), NOW()),
    (UUID(), 'Nairobi', NOW(), NOW());

INSERT INTO genders (gender_identity_UUID, gender_identity, created_at, updated_at) VALUES
    (UUID(), 'MALE', NOW(), NOW()),
    (UUID(), 'FEMALE', NOW(), NOW()),
    (UUID(), 'OTHER', NOW(), NOW());

INSERT INTO relationship_statuses (relationship_status_UUID, relationship_status, created_at, updated_at) VALUES
    (UUID(), 'Single', NOW(), NOW()),
    (UUID(), 'Engaged', NOW(), NOW()),
    (UUID(), 'Married', NOW(), NOW()),
    (UUID(), 'Separated', NOW(), NOW()),
    (UUID(), 'Divorced', NOW(), NOW()),
    (UUID(), 'Complicated', NOW(), NOW()),
    (UUID(), 'Widowed', NOW(), NOW()),
    (UUID(), 'Other', NOW(), NOW());

INSERT INTO payment_plans (plan_UUID, plan_name, created_at, updated_at) VALUES
    (UUID(), 'Buy to own', NOW(), NOW()),
    (UUID(), 'Rent to own', NOW(), NOW()),
    (UUID(), 'Mortgage', NOW(), NOW());

INSERT INTO mortgage_plans (plan_UUID, plan_name, created_at, updated_at) VALUES
    (UUID(), 'N/A', NOW(), NOW()),
    (UUID(), 'Individual Package', NOW(), NOW()),
    (UUID(), 'Group Package', NOW(), NOW()),
    (UUID(), 'Corporate Package', NOW(), NOW());

-- ALTER TABLE `payments` ADD `mrchant_request_id` VARCHAR(255) NULL DEFAULT NULL AFTER `invoice_number`, ADD `checkout_request_id` VARCHAR(255) NULL DEFAULT NULL AFTER `mrchant_request_id`, ADD `transaction_reference` VARCHAR(255) NULL DEFAULT NULL AFTER `checkout_request_id`;
-- ALTER TABLE `payments` ADD `result_code` INT(100) NULL DEFAULT NULL AFTER `transaction_reference`;




