x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<date>\d{4}-\d{2}-\d{2}) (?P<time>\d{2}:\d{2}:\d{2}.\d{3}) (?P<message>(?s:.*))$$'

version: "3.8"

services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx-proxy
  #   restart: always
  #   ports:
  #     - "443:443" # HTTPS
  #     - "80:80"   # HTTP (you can choose to redirect HTTP to HTTPS inside NGINX config)
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount NGINX config
  #     - ./certs:/etc/nginx/certs:ro           # Mount SSL certificates
  #   logging: *default-logging

# Frontend service
  community-app:
    image: openmf/web-app:master
    container_name: mifos-ui
    restart: always
    ports:
      - 8080:80
    # depends_on:
    #   - nginx

  loki:
    extends:
      file: ./config/docker/compose/observability.yml
      service: loki

  prometheus:
    extends:
      file: ./config/docker/compose/observability.yml
      service: prometheus
    depends_on:
    - loki

  grafana:
    extends:
      file: ./config/docker/compose/observability.yml
      service: grafana
    depends_on:
      - loki
      # - nginx

  tempo:
    extends:
      file: ./config/docker/compose/observability.yml
      service: tempo
    depends_on:
      - loki

  db:
    extends:
      file: ./config/docker/compose/mariadb.yml
      service: mariadb
    depends_on:
      - loki
    logging: *default-logging
    volumes:
      - /mnt/volume_nyc1_01/mariadb:/var/lib/mysql

  fineract:
    container_name: fineract-development
    extends:
      file: ./config/docker/compose/fineract.yml
      service: fineract
    ports:
      - "8443:8443"
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      loki:
        condition: service_started
      # nginx:
      #   condition: service_started
    env_file:
      - ./config/docker/env/aws.env
      - ./config/docker/env/fineract.env
      - ./config/docker/env/fineract-common.env
      - ./config/docker/env/fineract-mariadb.env
      - ./config/docker/env/tracing.env
      - ./config/docker/env/oltp.env
      - ./config/docker/env/prometheus.env
      # - ./config/docker/env/cloudwatch.env
      - ./config/docker/env/debug.env
    logging: *default-logging



